name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  bencode:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: tortue-bencode
    - name: Test
      run: cargo test --verbose
      working-directory: tortue-bencode
    - name: Bench
      run: cargo bench
      working-directory: tortue-bencode
    - name: Install Fuzz
      run: cargo install carg-fuzz
    - name: Fuzz
      run: cargo fuzz run random_write
      
